#include <fastGJK/fastGJK.cuh>
#include <fstream>
#include <string>
#include <vector>

#include "tool.cuh"
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest.h"

static std::vector<fastGJK::Vec3>
cubeVerts(fastGJK::val_t x, fastGJK::val_t y, fastGJK::val_t z, fastGJK::val_t halfExtent)
{
    using fastGJK::Vec3;
    return {
        Vec3(x - halfExtent, y - halfExtent, z - halfExtent),
        Vec3(x + halfExtent, y - halfExtent, z - halfExtent),
        Vec3(x - halfExtent, y + halfExtent, z - halfExtent),
        Vec3(x + halfExtent, y + halfExtent, z - halfExtent),
        Vec3(x - halfExtent, y - halfExtent, z + halfExtent),
        Vec3(x + halfExtent, y - halfExtent, z + halfExtent),
        Vec3(x - halfExtent, y + halfExtent, z + halfExtent),
        Vec3(x + halfExtent, y + halfExtent, z + halfExtent),
    };
}

TEST_SUITE_BEGIN("Test GJK");
TEST_CASE("Simple case")
{
    std::vector<fastGJK::Vec3> vertsA, vertsB;
    fastGJK::val_t             expected;

    SUBCASE("Two touching cubes")
    {
        vertsA   = cubeVerts(0, 0, 0, 2);
        vertsB   = cubeVerts(4, 0, 0, 2);
        expected = 0.0;
    }

    SUBCASE("Two separate cubes")
    {
        vertsA   = cubeVerts(0, 0, 0, 2);
        vertsB   = cubeVerts(5, 0, 0, 2);
        expected = 1.0;
    }

    SUBCASE("Two separate polyhedrons")
    {
        vertsA   = {{0.0, 0.0, 0.0},
                    {-1.0, 1.0, 0.0},
                    {-1.0, -1.0, 0.0},
                    {-1.0, 0.0, 1.0},
                    {-1.0, 0.0, -1.0},
                    {-2.0, 1.0, 1.0},
                    {-4.0, 2.0, 0.0},
                    {-4.0, -2.0, 0.0},
                    {-4.0, 0.0, 2.0},
                    {-4.0, 0.0, -2.0}};
        vertsB   = {{3.1415, 0.0, 0.0},
                    {5.1415, 1.0, -1.0},
                    {5.1415, -1.0, 1.0},
                    {5.1415, -1.0, -1.0},
                    {11.1415, 2.0, 2.0},
                    {11.1415, 2.0, -2.0},
                    {11.1415, -2.0, 2.0},
                    {11.1415, -2.0, -2.0},
                    {12.1415, 0.0, 3.0}};
        expected = 3.1415;
    }

    //! Generated by Gemini
    SUBCASE("Complex Face-to-Vertex collision")
    {
        vertsA   = {{3.0, 10.0, 1.0},
                    {11.0, 2.0, 5.0},
                    {9.0, 10.0, 7.0},
                    {5.0, 2.0, -1.0},
                    {2.0, 17.0, 8.0},
                    {14.0, 5.0, 14.0},
                    {-4.0, 5.0, -4.0},
                    {8.0, -7.0, 2.0},
                    {1.0, 3.0, 9.0},
                    {2.0, 8.0, 8.0}};
        vertsB   = {{9.0, 7.0, 1.0},
                    {9.0, 16.0, 1.0},
                    {17.0, 8.0, 5.0},
                    {5.0, 8.0, -7.0},
                    {13.0, 0.0, -3.0},
                    {15.0, 10.0, -5.0},
                    {7.0, 15.0, -6.0},
                    {19.0, 3.0, 0.0}};
        expected = 3.0;
    }

    //! Generated by Gemini
    SUBCASE("Complex Edge-to-Edge collision")
    {
        vertsA   = {{2.0, 5.0, 11.0},
                    {10.0, 9.0, 3.0},
                    {0.0, 7.0, 1.0},
                    {8.0, -1.0, 5.0},
                    {7.0, 3.0, -3.0},
                    {-1.0, -1.0, 5.0},
                    {2.0, -1.0, -1.0}};
        vertsB   = {{3.0, 13.0, 7.0},
                    {11.0, 5.0, 11.0},
                    {12.0, 13.0, 7.0},
                    {4.0, 9.0, 15.0},
                    {5.0, 17.0, 11.0},
                    {13.0, 9.0, 15.0},
                    {10.0, 15.0, 15.0}};
        expected = 3.0;
    }

    //! Generated by Gemini
    SUBCASE("Deep Penetration (Intersecting polyhedrons)")
    {
        vertsA   = {{0.0, 5.0, 0.0},
                    {0.0, -5.0, 0.0},
                    {5.0, 0.0, 0.0},
                    {-5.0, 0.0, 0.0},
                    {0.0, 0.0, 5.0},
                    {0.0, 0.0, -5.0},
                    {2.0, 2.0, 2.0},
                    {-2.0, -2.0, -2.0}};
        vertsB   = {{1.0, 6.0, 1.0},
                    {1.0, -4.0, 1.0},
                    {6.0, 1.0, 1.0},
                    {-4.0, 1.0, 1.0},
                    {1.0, 1.0, 6.0},
                    {1.0, 1.0, -4.0},
                    {3.0, 3.0, 3.0},
                    {-1.0, -1.0, -1.0}};
        expected = 0.0;
    }

    // Set up GJKState
    int      nA      = static_cast<int>(vertsA.size());
    int      nB      = static_cast<int>(vertsB.size());
    int     *nvertsA = new int[1]{nA};
    int     *nvertsB = new int[1]{nB};
    GJKState state(1, nvertsA, nvertsB);

    // Copy vertices into state
    for (int j = 0; j < nA; ++j)
        state.hullsA.host[0].verts[j] = vertsA[j];
    for (int j = 0; j < nB; ++j)
        state.hullsB.host[0].verts[j] = vertsB[j];
    state.distances_expected[0] = expected;

    // Copy input data to GPU
    state.copyInputToGpu();

    // Run
    fastGJK::warp::gjk_process(
        state.hullsA.device, state.hullsB.device, state.n, state.simplices.device, state.distances.device);

    // Copy result to host
    state.copyOutputToCpu();

    // Check
    REQUIRE(state.distances.host[0] == doctest::Approx(expected));
}

TEST_CASE("Complex case")
{
    std::string filename;

    SUBCASE("Corner case") { filename = "data/input_corner1.txt"; }
    SUBCASE("Dataset with 1000 samples") { filename = "data/input_1000.txt"; }

    // Determine data shape
    unsigned int n;
    int         *nvertsA, *nvertsB;
    REQUIRE(readDatasetMetadata(filename, n, nvertsA, nvertsB));
    GJKState state(n, nvertsA, nvertsB);

    // Read dataset
    readDataset(filename, state);

    // Copy input data to GPU
    state.copyInputToGpu();

    // Run
    fastGJK::warp::gjk_process(
        state.hullsA.device, state.hullsB.device, state.n, state.simplices.device, state.distances.device);

    // Copy result to host
    state.copyOutputToCpu();

    // Verify results
    for (unsigned int i = 0; i < n; i++) {
        fastGJK::val_t actual   = state.distances.host[i];
        fastGJK::val_t expected = state.distances_expected[i];
        INFO("Pair index: ", i);
        INFO("Actual: ", actual, "; Expected: ", expected);
        fastGJK::val_t tol = std::max(fastGJK::val_t(0.01), std::abs(expected) * fastGJK::val_t(0.01));
        REQUIRE(std::abs(actual - expected) < tol);
    }
}

TEST_SUITE_END();
