#include <fastGJK/fastGJK.cuh>
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <algorithm>
#include <cmath>
#include <fstream>
#include <random>

#include "common.cuh"
#include "doctest.h"

static fastGJK::ConvexHull createCube(fastGJK::val_t x, fastGJK::val_t y, fastGJK::val_t z, fastGJK::val_t halfExtent)
{
    using namespace fastGJK;
    ConvexHull hull;
    hull.n     = 8;
    hull.verts = new Vec3[8]{
        Vec3(x - halfExtent, y - halfExtent, z - halfExtent),
        Vec3(x + halfExtent, y - halfExtent, z - halfExtent),
        Vec3(x - halfExtent, y + halfExtent, z - halfExtent),
        Vec3(x + halfExtent, y + halfExtent, z - halfExtent),
        Vec3(x - halfExtent, y - halfExtent, z + halfExtent),
        Vec3(x + halfExtent, y - halfExtent, z + halfExtent),
        Vec3(x - halfExtent, y + halfExtent, z + halfExtent),
        Vec3(x + halfExtent, y + halfExtent, z + halfExtent),
    };
    return hull;
}

static fastGJK::ConvexHull createPoly(std::initializer_list<fastGJK::Vec3> verts)
{
    fastGJK::ConvexHull hull;
    hull.n     = static_cast<int>(verts.size());
    hull.verts = new fastGJK::Vec3[hull.n];
    int i      = 0;
    for (const auto &v : verts)
        hull.verts[i++] = v;
    return hull;
}

TEST_SUITE_BEGIN("Test GJK");
TEST_CASE("Simple case")
{
    fastGJK::ConvexHull *objA_device, *objB_device;
    fastGJK::Simplex    *simplex_device, *simplex_host;
    fastGJK::Vec3       *verts_device;
    fastGJK::val_t      *distance_device, *distance_host;
    fastGJK::ConvexHull  objA_host, objB_host;
    fastGJK::val_t       expected;

    SUBCASE("Two touching cubes")
    {
        objA_host = createCube(0, 0, 0, 2);
        objB_host = createCube(4, 0, 0, 2);
        expected  = 0.0;
    }

    SUBCASE("Two separate cubes")
    {
        objA_host = createCube(0, 0, 0, 2);
        objB_host = createCube(5, 0, 0, 2);
        expected  = 1.0;
    }

    SUBCASE("Two separate polyhedrons")
    {
        objA_host = createPoly({{0.0, 0.0, 0.0},
                                {-1.0, 1.0, 0.0},
                                {-1.0, -1.0, 0.0},
                                {-1.0, 0.0, 1.0},
                                {-1.0, 0.0, -1.0},
                                {-2.0, 1.0, 1.0},
                                {-4.0, 2.0, 0.0},
                                {-4.0, -2.0, 0.0},
                                {-4.0, 0.0, 2.0},
                                {-4.0, 0.0, -2.0}});
        objB_host = createPoly({{3.1415, 0.0, 0.0},
                                {5.1415, 1.0, -1.0},
                                {5.1415, -1.0, 1.0},
                                {5.1415, -1.0, -1.0},
                                {11.1415, 2.0, 2.0},
                                {11.1415, 2.0, -2.0},
                                {11.1415, -2.0, 2.0},
                                {11.1415, -2.0, -2.0},
                                {12.1415, 0.0, 3.0}});
        expected  = 3.1415;
    }

    //! Generated by Gemini
    SUBCASE("Complex Face-to-Vertex collision")
    {
        objA_host = createPoly({{3.0, 10.0, 1.0},
                                {11.0, 2.0, 5.0},
                                {9.0, 10.0, 7.0},
                                {5.0, 2.0, -1.0},
                                {2.0, 17.0, 8.0},
                                {14.0, 5.0, 14.0},
                                {-4.0, 5.0, -4.0},
                                {8.0, -7.0, 2.0},
                                {1.0, 3.0, 9.0},
                                {2.0, 8.0, 8.0}});
        objB_host = createPoly({{9.0, 7.0, 1.0},
                                {9.0, 16.0, 1.0},
                                {17.0, 8.0, 5.0},
                                {5.0, 8.0, -7.0},
                                {13.0, 0.0, -3.0},
                                {15.0, 10.0, -5.0},
                                {7.0, 15.0, -6.0},
                                {19.0, 3.0, 0.0}});
        expected  = 3.0;
    }

    //! Generated by Gemini
    SUBCASE("Complex Edge-to-Edge collision")
    {
        objA_host = createPoly({{2.0, 5.0, 11.0},
                                {10.0, 9.0, 3.0},
                                {0.0, 7.0, 1.0},
                                {8.0, -1.0, 5.0},
                                {7.0, 3.0, -3.0},
                                {-1.0, -1.0, 5.0},
                                {2.0, -1.0, -1.0}});
        objB_host = createPoly({{3.0, 13.0, 7.0},
                                {11.0, 5.0, 11.0},
                                {12.0, 13.0, 7.0},
                                {4.0, 9.0, 15.0},
                                {5.0, 17.0, 11.0},
                                {13.0, 9.0, 15.0},
                                {10.0, 15.0, 15.0}});
        expected  = 3.0;
    }

    //! Generated by Gemini
    SUBCASE("Deep Penetration (Intersecting polyhedrons)")
    {
        objA_host = createPoly({{0.0, 5.0, 0.0},
                                {0.0, -5.0, 0.0},
                                {5.0, 0.0, 0.0},
                                {-5.0, 0.0, 0.0},
                                {0.0, 0.0, 5.0},
                                {0.0, 0.0, -5.0},
                                {2.0, 2.0, 2.0},
                                {-2.0, -2.0, -2.0}});
        objB_host = createPoly({{1.0, 6.0, 1.0},
                                {1.0, -4.0, 1.0},
                                {6.0, 1.0, 1.0},
                                {-4.0, 1.0, 1.0},
                                {1.0, 1.0, 6.0},
                                {1.0, 1.0, -4.0},
                                {3.0, 3.0, 3.0},
                                {-1.0, -1.0, -1.0}});
        expected  = 0.0;
    }

    // Run
    prepareDataOnDevice(
        &objA_host, &objB_host, objA_device, objB_device, verts_device, simplex_device, distance_device, 1);
    fastGJK::warp::gjk_process(objA_device, objB_device, 1, simplex_device, distance_device);
    copyResultToHost(simplex_device, distance_device, simplex_host, distance_host, 1);

    // Check
    REQUIRE(*distance_host == doctest::Approx(expected));

    // Free pointers
    freeDeviceMem(objA_device, objB_device, verts_device, simplex_device, distance_device);
    freeHostMem(simplex_host, distance_host);
    delete[] objA_host.verts;
    delete[] objB_host.verts;
}

TEST_CASE("Complex case")
{
    fastGJK::ConvexHull *hullsA_host, *hullsB_host;
    fastGJK::val_t      *distances_host, *expected;
    fastGJK::Simplex    *simplices_host;
    unsigned int         n;
    std::string          filename;

    SUBCASE("Corner case") { filename = "data/input_corner1.txt"; }
    SUBCASE("Dataset with 1000 samples") { filename = "data/input_1000.txt"; }

    // Load data to main memory
    REQUIRE(readDataset(filename, hullsA_host, hullsB_host, expected, n));

    // Copy data to device memory
    fastGJK::ConvexHull *hullsA_device, *hullsB_device;
    fastGJK::val_t      *distances_device;
    fastGJK::Simplex    *simplices_device;
    fastGJK::Vec3       *verts_device;
    prepareDataOnDevice(
        hullsA_host, hullsB_host, hullsA_device, hullsB_device, verts_device, simplices_device, distances_device, n);

    // Run
    fastGJK::warp::gjk_process(hullsA_device, hullsB_device, n, simplices_device, distances_device);

    // Copy result to host
    copyResultToHost(simplices_device, distances_device, simplices_host, distances_host, n);


    // Verify results
    for (unsigned int i = 0; i < n; i++) {
        INFO("Pair index: ", i);
        INFO("Actual: ", distances_host[i], "; Expected: ", expected[i]);
        fastGJK::val_t tol = std::max(fastGJK::val_t(0.01), std::abs(expected[i]) * fastGJK::val_t(0.01));
        CHECK(std::abs(distances_host[i] - expected[i]) < tol);
    }

    // Free resources
    freeDeviceMem(hullsA_device, hullsB_device, verts_device, simplices_device, distances_device);
    freeHostMem(simplices_host, distances_host);
    for (unsigned int i = 0; i < n; ++i) {
        delete[] hullsA_host[i].verts;
        delete[] hullsB_host[i].verts;
    }
    delete[] hullsA_host;
    delete[] hullsB_host;
    delete[] expected;
}


TEST_SUITE_END();
