#include <fastGJK/fastGJK.cuh>
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <algorithm>
#include <cmath>
#include <random>

#include "common.cuh"
#include "doctest.h"

static fastGJK::ConvexHull createCube(fastGJK::val_t x, fastGJK::val_t y, fastGJK::val_t z, fastGJK::val_t halfExtent)
{
    using namespace fastGJK;
    ConvexHull hull;
    hull.n     = 8;
    hull.verts = new Vec3[8]{
        Vec3(x - halfExtent, y - halfExtent, z - halfExtent),
        Vec3(x + halfExtent, y - halfExtent, z - halfExtent),
        Vec3(x - halfExtent, y + halfExtent, z - halfExtent),
        Vec3(x + halfExtent, y + halfExtent, z - halfExtent),
        Vec3(x - halfExtent, y - halfExtent, z + halfExtent),
        Vec3(x + halfExtent, y - halfExtent, z + halfExtent),
        Vec3(x - halfExtent, y + halfExtent, z + halfExtent),
        Vec3(x + halfExtent, y + halfExtent, z + halfExtent),
    };
    return hull;
}

static fastGJK::ConvexHull createPoly(std::initializer_list<fastGJK::Vec3> verts)
{
    fastGJK::ConvexHull hull;
    hull.n     = static_cast<int>(verts.size());
    hull.verts = new fastGJK::Vec3[hull.n];
    int i      = 0;
    for (const auto &v : verts)
        hull.verts[i++] = v;
    return hull;
}

TEST_SUITE_BEGIN("Test GJK");
TEST_CASE("Single collision")
{
    fastGJK::ConvexHull *objA_device, *objB_device;
    fastGJK::Simplex    *simplex_device, *simplex_host;
    fastGJK::Vec3       *verts_device;
    fastGJK::val_t      *distance_device, *distance_host;
    fastGJK::ConvexHull  objA_host, objB_host;
    fastGJK::val_t       expected;

    SUBCASE("Two touching cubes")
    {
        objA_host = createCube(0, 0, 0, 2);
        objB_host = createCube(4, 0, 0, 2);
        expected  = 0.0;
    }

    SUBCASE("Two separate cubes")
    {
        objA_host = createCube(0, 0, 0, 2);
        objB_host = createCube(5, 0, 0, 2);
        expected  = 1.0;
    }

    SUBCASE("Two separate polyhedrons")
    {
        objA_host = createPoly({{0.0, 0.0, 0.0},
                                {-1.0, 1.0, 0.0},
                                {-1.0, -1.0, 0.0},
                                {-1.0, 0.0, 1.0},
                                {-1.0, 0.0, -1.0},
                                {-2.0, 1.0, 1.0},
                                {-4.0, 2.0, 0.0},
                                {-4.0, -2.0, 0.0},
                                {-4.0, 0.0, 2.0},
                                {-4.0, 0.0, -2.0}});
        objB_host = createPoly({{3.1415, 0.0, 0.0},
                                {5.1415, 1.0, -1.0},
                                {5.1415, -1.0, 1.0},
                                {5.1415, -1.0, -1.0},
                                {11.1415, 2.0, 2.0},
                                {11.1415, 2.0, -2.0},
                                {11.1415, -2.0, 2.0},
                                {11.1415, -2.0, -2.0},
                                {12.1415, 0.0, 3.0}});
        expected  = 3.1415;
    }

    //! Generated by Gemini
    SUBCASE("Complex Face-to-Vertex collision")
    {
        objA_host = createPoly({{3.0, 10.0, 1.0},
                                {11.0, 2.0, 5.0},
                                {9.0, 10.0, 7.0},
                                {5.0, 2.0, -1.0},
                                {2.0, 17.0, 8.0},
                                {14.0, 5.0, 14.0},
                                {-4.0, 5.0, -4.0},
                                {8.0, -7.0, 2.0},
                                {1.0, 3.0, 9.0},
                                {2.0, 8.0, 8.0}});
        objB_host = createPoly({{9.0, 7.0, 1.0},
                                {9.0, 16.0, 1.0},
                                {17.0, 8.0, 5.0},
                                {5.0, 8.0, -7.0},
                                {13.0, 0.0, -3.0},
                                {15.0, 10.0, -5.0},
                                {7.0, 15.0, -6.0},
                                {19.0, 3.0, 0.0}});
        expected  = 3.0;
    }

    //! Generated by Gemini
    SUBCASE("Complex Edge-to-Edge collision")
    {
        objA_host = createPoly({{2.0, 5.0, 11.0},
                                {10.0, 9.0, 3.0},
                                {0.0, 7.0, 1.0},
                                {8.0, -1.0, 5.0},
                                {7.0, 3.0, -3.0},
                                {-1.0, -1.0, 5.0},
                                {2.0, -1.0, -1.0}});
        objB_host = createPoly({{3.0, 13.0, 7.0},
                                {11.0, 5.0, 11.0},
                                {12.0, 13.0, 7.0},
                                {4.0, 9.0, 15.0},
                                {5.0, 17.0, 11.0},
                                {13.0, 9.0, 15.0},
                                {10.0, 15.0, 15.0}});
        expected  = 3.0;
    }

    //! Generated by Gemini
    SUBCASE("Deep Penetration (Intersecting polyhedrons)")
    {
        objA_host = createPoly({{0.0, 5.0, 0.0},
                                {0.0, -5.0, 0.0},
                                {5.0, 0.0, 0.0},
                                {-5.0, 0.0, 0.0},
                                {0.0, 0.0, 5.0},
                                {0.0, 0.0, -5.0},
                                {2.0, 2.0, 2.0},
                                {-2.0, -2.0, -2.0}});
        objB_host = createPoly({{1.0, 6.0, 1.0},
                                {1.0, -4.0, 1.0},
                                {6.0, 1.0, 1.0},
                                {-4.0, 1.0, 1.0},
                                {1.0, 1.0, 6.0},
                                {1.0, 1.0, -4.0},
                                {3.0, 3.0, 3.0},
                                {-1.0, -1.0, -1.0}});
        expected  = 0.0;
    }

    // Run
    prepareDataOnDevice(
        &objA_host, &objB_host, objA_device, objB_device, verts_device, simplex_device, distance_device, 1);
    fastGJK::warp::gjk_process(objA_device, objB_device, 1, simplex_device, distance_device);
    copyResultToHost(simplex_device, distance_device, simplex_host, distance_host, 1);

    // Check
    REQUIRE(*distance_host == doctest::Approx(expected));

    // Free pointers
    freeDeviceMem(objA_device, objB_device, verts_device, simplex_device, distance_device);
    freeHostMem(simplex_host, distance_host);
    delete[] objA_host.verts;
    delete[] objB_host.verts;
}

// Generate box vertices: 8 corners + random surface points to reach nVerts
static void generateBoxVerts(fastGJK::Vec3 *verts,
                             int            nVerts,
                             fastGJK::val_t cx,
                             fastGJK::val_t cy,
                             fastGJK::val_t cz,
                             fastGJK::val_t hx,
                             fastGJK::val_t hy,
                             fastGJK::val_t hz,
                             std::mt19937  &rng)
{
    using namespace fastGJK;
    int idx = 0;
    for (int sx = -1; sx <= 1; sx += 2)
        for (int sy = -1; sy <= 1; sy += 2)
            for (int sz = -1; sz <= 1; sz += 2)
                verts[idx++] = Vec3(cx + sx * hx, cy + sy * hy, cz + sz * hz);

    std::uniform_int_distribution<int>    faceDist(0, 5);
    std::uniform_real_distribution<val_t> uvDist(val_t(-1), val_t(1));
    for (int j = 8; j < nVerts; j++) {
        val_t u = uvDist(rng), v = uvDist(rng);
        val_t x, y, z;
        switch (faceDist(rng)) {
        case 0:
            x = cx + hx;
            y = cy + u * hy;
            z = cz + v * hz;
            break;
        case 1:
            x = cx - hx;
            y = cy + u * hy;
            z = cz + v * hz;
            break;
        case 2:
            x = cx + u * hx;
            y = cy + hy;
            z = cz + v * hz;
            break;
        case 3:
            x = cx + u * hx;
            y = cy - hy;
            z = cz + v * hz;
            break;
        case 4:
            x = cx + u * hx;
            y = cy + v * hy;
            z = cz + hz;
            break;
        default:
            x = cx + u * hx;
            y = cy + v * hy;
            z = cz - hz;
            break;
        }
        verts[j] = Vec3(x, y, z);
    }
}

//! Generate by Claude code
TEST_CASE("Batched collision")
{
    using namespace fastGJK;
    constexpr int n        = 3000;
    constexpr int maxVerts = 256;
    constexpr int minVerts = 8; // at least 8 for box corners

    std::mt19937                          rng(42);
    std::uniform_int_distribution<int>    vertDist(minVerts, maxVerts);
    std::uniform_real_distribution<val_t> centerDist(val_t(-50), val_t(50));
    std::uniform_real_distribution<val_t> halfExtDist(val_t(0.5), val_t(5));

    auto *objA_host = new ConvexHull[n];
    auto *objB_host = new ConvexHull[n];
    auto *expected  = new val_t[n];

    for (int i = 0; i < n; i++) {
        int   nA = vertDist(rng), nB = vertDist(rng);
        val_t cAx = centerDist(rng), cAy = centerDist(rng), cAz = centerDist(rng);
        val_t hAx = halfExtDist(rng), hAy = halfExtDist(rng), hAz = halfExtDist(rng);
        val_t cBx = centerDist(rng), cBy = centerDist(rng), cBz = centerDist(rng);
        val_t hBx = halfExtDist(rng), hBy = halfExtDist(rng), hBz = halfExtDist(rng);

        objA_host[i].n     = nA;
        objA_host[i].verts = new Vec3[nA];
        objB_host[i].n     = nB;
        objB_host[i].verts = new Vec3[nB];

        generateBoxVerts(objA_host[i].verts, nA, cAx, cAy, cAz, hAx, hAy, hAz, rng);
        generateBoxVerts(objB_host[i].verts, nB, cBx, cBy, cBz, hBx, hBy, hBz, rng);

        // Analytical box-box distance
        val_t dx    = std::max(val_t(0), std::abs(cAx - cBx) - hAx - hBx);
        val_t dy    = std::max(val_t(0), std::abs(cAy - cBy) - hAy - hBy);
        val_t dz    = std::max(val_t(0), std::abs(cAz - cBz) - hAz - hBz);
        expected[i] = std::sqrt(dx * dx + dy * dy + dz * dz);
    }

    // Run on GPU
    ConvexHull *objA_device, *objB_device;
    Simplex    *simplex_device, *simplex_host;
    Vec3       *verts_device;
    val_t      *distance_device, *distance_host;

    prepareDataOnDevice(
        objA_host, objB_host, objA_device, objB_device, verts_device, simplex_device, distance_device, n);
    warp::gjk_process(objA_device, objB_device, n, simplex_device, distance_device);
    copyResultToHost(simplex_device, distance_device, simplex_host, distance_host, n);

    // Verify results
    for (int i = 0; i < n; i++) {
        INFO("Pair index: ", i);
        val_t tol = std::max(val_t(0.01), std::abs(expected[i]) * val_t(0.01));
        CHECK(std::abs(distance_host[i] - expected[i]) < tol);
    }

    // Cleanup
    freeDeviceMem(objA_device, objB_device, verts_device, simplex_device, distance_device);
    freeHostMem(simplex_host, distance_host);
    for (int i = 0; i < n; i++) {
        delete[] objA_host[i].verts;
        delete[] objB_host[i].verts;
    }
    delete[] objA_host;
    delete[] objB_host;
    delete[] expected;
}


TEST_SUITE_END();
